### ISSUE TITLE
Small-radius blur is very slow, severely impacting benchmarks

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#173] opened 2019-09-04 01:57 UTC
Currently resvg uses linear-complexity box blur only if both X and Y radii are greater than 2px.

Making resvg always use box blur cuts down Oxygen icon theme render time from 155 seconds to 113 seconds (with Cairo backend), which is a 27% performance improvement. This puts resvg ahead of rsvg, making resvg 13% faster than rsvg even on this test.

The `image` crate is reported to contain a blur implementation that's faster than `fastblur` for small radii. Perhaps that could be used instead of the current implementation.

Alternatively, Firefox is [reported](https://github.com/RazrFalcon/resvg/issues/125#issuecomment-515463194) to use box blur for all radii. Perhaps this is something worth pursuing.

**Comment by RazrFalcon** [comment] 2019-09-04 08:56
Yes, this is expected. The problem is that by the SVG spec, bbox blur should be used only for radii >= 2. The current implementation matches the one in Inkscape. Yes it's slower, but more correct. And correctness is the goal.

I'm not sure what blur implementation is used in the `image` crate.

**Comment by RazrFalcon** [comment] 2019-09-04 09:13
Also, all filters are slow at the moment (also clipPath and opacity). I should find a time to benchmark all of them. 

Basically, the current goal is correctness, not performance.

**Comment by RazrFalcon** [comment] 2019-09-04 10:58
Strangely, there are almost no visual changes between IIR and box blur. At least on my test.

Here `cairo-backend` uses box blur, while `qt-backend` uses IIR. Diff is relative to Chrome.

![e-feGaussianBlur-002](https://user-images.githubusercontent.com/725494/64249340-1d5a4580-cf1c-11e9-8a16-9e87dfd07337.png)

![e-feGaussianBlur-001](https://user-images.githubusercontent.com/725494/64249348-20553600-cf1c-11e9-864d-89f583836493.png)

**Comment by RazrFalcon** [comment] 2019-09-04 11:23
Also, according to simple benchmarks, IIR is only 2x slower that box blur.

```
test box_blur_100px ... bench:   1,203,795 ns/iter (+/- 5,115)
test iir_blur_100px ... bench:   2,629,032 ns/iter (+/- 14,172)
test box_blur_500px ... bench:  31,291,022 ns/iter (+/- 263,622)
test iir_blur_500px ... bench:  66,227,496 ns/iter (+/- 137,204)
```

**Comment by RazrFalcon** [comment] 2023-05-21 13:39
Out of scope.

**Closed by RazrFalcon** 2023-05-21 13:39 UTC
