### ISSUE TITLE
Incorrect edge using gaussian blur

### ISSUE THREAD

**Issue by wangrl2016** [RazrFalcon/resvg#324] opened 2020-10-22 11:05 UTC
The zip has a svg file, the background image using guassian blur, but the edge show white line.

[gaussian_blur_svg.zip](https://github.com/RazrFalcon/resvg/files/5422193/gaussian_blur_svg.zip)

![sceenshot](https://user-images.githubusercontent.com/49860767/96863417-6ca16380-1499-11eb-883d-9f617144d35c.png)

**Comment by RazrFalcon** [comment] 2020-10-23 16:59
Duplicate of #241

**Comment by RazrFalcon** [comment] 2020-10-23 16:59
This is a know bug and it's pretty hard to fix.

**Closed by RazrFalcon** 2020-10-23 16:59 UTC

**Comment by RazrFalcon** [comment] 2023-05-21 13:34
Fixed in v0.33
