### ISSUE TITLE
FreeBSD logo causes hang

### ISSUE THREAD

**Issue by Helios-vmg** [RazrFalcon/resvg#616] opened 2023-04-22 02:43 UTC
![Freebsd_logo](https://user-images.githubusercontent.com/6202851/233757750-6ef63045-4467-4fbe-a3b9-5443dc44c34e.svg)

To reproduce, run
```
$ revsg Freebsd_logo.svg output.png
```
(I know the file doesn't render properly basically anywhere, but the library still shouldn't hang.)

**Comment by RazrFalcon** [comment] 2023-04-22 06:22
Duplicate of #257

**Closed by RazrFalcon** 2023-04-22 06:22 UTC

**Comment by RazrFalcon** [comment] 2023-04-22 06:24
Yes, this is a known issue with `BackgroundImage` for filters implementation. It will render it eventually. It just takes a lot of time.

And one of the reasons why this image is broken everywhere is that no one really supports `BackgroundImage`. None of the browsers do.

**Comment by RazrFalcon** [comment] 2023-04-23 15:12
"Fixed" by removing `enable-background` feature altogether. It was deprecated in SVG 2 anyway.
