### ISSUE TITLE
can' determine size

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#261] opened 2020-03-02 21:36 UTC
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/3/3f/Feedbin-Favicon-tag.svg)
|ink|![Feedbin-Favicon-tag](https://user-images.githubusercontent.com/15687581/75719916-e94abc00-5cd5-11ea-9d96-0fbac8adfd1e.png)
|resvg|no image
|rsvg|![Feedbin-Favicon-tag_rsvg](https://user-images.githubusercontent.com/15687581/75719932-ee0f7000-5cd5-11ea-861e-59d33f74f742.png)

#### What should have happened?
same as chrome
![Screenshot from 2020-03-02 22-34-50](https://user-images.githubusercontent.com/15687581/75719994-0b443e80-5cd6-11ea-876b-19b21575b4d1.png)

same as QtSVG
![Screenshot from 2020-03-02 22-35-30](https://user-images.githubusercontent.com/15687581/75720079-257e1c80-5cd6-11ea-8c91-515eb882e1ac.png)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Feedbin-Favicon-tag.svg

author Feedbin Inc.

license https://commons.wikimedia.org/wiki/Category:Expat/MIT_License

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment] 2020-03-03 02:48
Duplicate of #40

**Closed by RazrFalcon** 2020-03-03 02:48 UTC
