### ISSUE TITLE
No match for any font generic names or substituted names

### ISSUE THREAD

**Issue by da2x** [RazrFalcon/resvg#480] opened 2021-11-16 06:35 UTC
> Warning (in usvg::text::convert:424): No match for 'Courier,monospace' font-family
> Warning (in usvg::text::convert:424): No match for 'Helvetica,Arial,sans-serif' font-family.
> Warning (in usvg::text::convert:424): No match for 'sans-serif' font-family.

The warnings are kind of correct, but also wrong. There are no fonts with these names installed on the system. However, FontConfig is set up with substitutions for all the named fonts, and it has defaults for the generic font names defined. This is the default in most Linux distributions. I’m not sure what further details you need.

Fedora Linux 35, resvg 0.19.0

**Comment by RazrFalcon** [comment] 2021-11-16 12:28
Fontconfig is not supported and not planned. C API is a minefield and not thread-safe (afaik) and Rust version is not available.

Also, it looks like a parsing error. Warning should contain a single family name. Can you send me the file or at east the `font-family` attribute?

**Comment by da2x** [comment] 2021-11-16 22:26
> Anyway, you basically have to configure resvg's fontdb yourself. Not sure if you're are using resvg as a library or a executable, but both have extensive API for defining fonts.

I’m using the executable.

Adding `--sans-serif-family "Nimbus Sans" --monospace-family "Nimbus Mono"` arguments make the error go away. Linux doesn’t have the default fonts you specify.

> Fontconfig is not supported and not planned. C API is a minefield and not thread-safe (afaik) and Rust version is not available.

Fair enough. Would you be willing to add the default font substitutions to fontdb, though? By default, I mean the PostScript level 1 fonts every platform is supposed to support. I wrote [an article about these](https://www.ctrl.blog/entry/font-stack-text.html) a few months back.

The operating systems perform these when substitutions when you use their APIs or something like FontConfig. But I guess you need to hardcode them as resvg is doing it’s own thing entirely.

Windows:
* Helvetica => Arial
* Times => Times New Roman
* Courier=>Courier New

Linux:
* Helvetica=>Nimbus Sans
* Times=>Nimbus Roman
* Courier=>Nimbus Mono

Linux (Windows compatibility, not PostScript):
* Arial=>Liberation Sans
* Times New Roman=>Liberation Serif
* Courier New=>Liberation Mono

Mac just ships the PostScript fonts by default. The Nimbus/Liberation fonts are both metrically compatible. Both are equal options for substitutions, but the above is FontConfig’s default set up. Most Linux distributions ship in full or in part either or both Nimbus and Liberation.

This should fix the defaults you’ve set for the generic names on most Linux distributions.

> Also, it looks like a parsing error. Warning should contain a single family name. Can you send me the file or at east the `font-family` attribute?

It’s set to exactly what’s shown in the warnings, so e.g. `Helvetica,Arial,sans-serif`.

But you’re logging the entire attribute, not just the parts of it. So, not a bug.

https://github.com/RazrFalcon/resvg/blob/7c89269337d0fb4ff673d2a196cffe8926399d81/usvg/src/text/convert.rs#L424

**Comment by RazrFalcon** [comment] 2021-11-16 22:46
>Linux doesn’t have the default fonts you specify.

Linux doesn't have default fonts do begin with. This is oxymoron. So without full FontConfig support, hardcoded values are the next best thing.
Proper fonts resolution is a low priority issue, because you should not rely on fallback fonts to begin with.

>This should fix the defaults you’ve set for the generic names on most Linux distributions.

My linux distro, gentoo, doesn't have any of those fonts.

>By default, I mean the PostScript level 1 fonts every platform is supposed to support.

>You also probably want to change the defaults to the PostScript font names instead of Microsoft’s we-refuse-to-pay-the-licenses-on-these-fonts lookalikes. Name substitutions can sot them back in again.

resvg uses family names, not PostScript names. As per CSS spec.

The main problem here is that fonts resolving is not specified and every browser, app, framework, etc are doing their own thing. There is no _correct_ behaviour.

**Comment by RazrFalcon** [comment] 2021-12-08 00:50
Not a bug.

**Closed by RazrFalcon** 2021-12-08 00:50 UTC
