### ISSUE TITLE
[μsvg] breaks all embedded jpeg-images by replacing it to invalid MIME-type jpg

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#569] opened 2023-01-10 18:11 UTC
## Input (valid jpeg-MIME-type)
![Input](https://user-images.githubusercontent.com/15687581/211606931-8c3798db-59d7-41b2-b449-671f7caa08d2.svg)

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="80" height="80" usvg:version="0.9.1" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg" xmlns:usvg="https://github.com/RazrFalcon/resvg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <image x="8" y="8" width="64" height="64" xlink:href="data:image/jpeg;base64,    
/9j/2wBDAP//////////////////////////////////////////////////////
////////////////////////////////2wBDAf//////////////////////////
////////////////////////////////////////////////////////////wgAR
CABAAEADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQAC/8QAFQEBAQAA
AAAAAAAAAAAAAAAAAAH/2gAMAwEAAhADEAAAAWsxrMgwMMrmbEtVlcgxFSVVVQSR
SDQMJFH/xAAUEAEAAAAAAAAAAAAAAAAAAABg/9oACAEBAAEFAgH/xAAUEQEAAAAA
AAAAAAAAAAAAAABA/9oACAEDAQE/AQf/xAAUEQEAAAAAAAAAAAAAAAAAAABA/9oA
CAECAQE/AQf/xAAUEAEAAAAAAAAAAAAAAAAAAABg/9oACAEBAAY/AgH/xAAbEAAC
AwEBAQAAAAAAAAAAAAAAARARMSFBIP/aAAgBAQABPyGbL+uoQzr+MZotHphrhlFO
aZQhlFFcK4UihDNRh4eDllCEMZ4Kez2f/9oADAMBAAIAAwAAABAVvf5uBDd4QyYe
Yq//xAAYEQADAQEAAAAAAAAAAAAAAAAAARARIP/aAAgBAwEBPxA02OofOX//xAAY
EQEBAQEBAAAAAAAAAAAAAAAAARExEP/aAAgBAgEBPxBjHE9qc9vErY2LX//EACMQ
AQACAgEEAQUAAAAAAAAAAAEAESExQRBRYXEggaGx4fD/2gAIAQEAAT8Q6vAzDg4+
Kt0R5Jz7zj3hsILdPW8kwPECL1Ao9TA8S8nRcHM98wB2dVHZPfMXDxNiA26lExEU
SAsyjcRs1NmbEKo5iOX4hlf3mOAepsREN4htmxCxY/SWpvXmbpHkhWk+0cZ7/fQl
wE0kbdoCN4iK3iCOzG3aQKn/2Q==
"/>
</svg>
```

## Output (invalid jpg-MIME-type)
![Output](https://user-images.githubusercontent.com/15687581/211606981-4b07f575-b1b5-435a-93f2-1d77832357ee.svg)

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="80" height="80" usvg:version="0.9.1" viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg" xmlns:usvg="https://github.com/RazrFalcon/resvg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <image x="8" y="8" width="64" height="64" xlink:href="data:image/jpg;base64,    
/9j/2wBDAP//////////////////////////////////////////////////////
////////////////////////////////2wBDAf//////////////////////////
////////////////////////////////////////////////////////////wgAR
CABAAEADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQAC/8QAFQEBAQAA
AAAAAAAAAAAAAAAAAAH/2gAMAwEAAhADEAAAAWsxrMgwMMrmbEtVlcgxFSVVVQSR
SDQMJFH/xAAUEAEAAAAAAAAAAAAAAAAAAABg/9oACAEBAAEFAgH/xAAUEQEAAAAA
AAAAAAAAAAAAAABA/9oACAEDAQE/AQf/xAAUEQEAAAAAAAAAAAAAAAAAAABA/9oA
CAECAQE/AQf/xAAUEAEAAAAAAAAAAAAAAAAAAABg/9oACAEBAAY/AgH/xAAbEAAC
AwEBAQAAAAAAAAAAAAAAARARMSFBIP/aAAgBAQABPyGbL+uoQzr+MZotHphrhlFO
aZQhlFFcK4UihDNRh4eDllCEMZ4Kez2f/9oADAMBAAIAAwAAABAVvf5uBDd4QyYe
Yq//xAAYEQADAQEAAAAAAAAAAAAAAAAAARARIP/aAAgBAwEBPxA02OofOX//xAAY
EQEBAQEBAAAAAAAAAAAAAAAAARExEP/aAAgBAgEBPxBjHE9qc9vErY2LX//EACMQ
AQACAgEEAQUAAAAAAAAAAAEAESExQRBRYXEggaGx4fD/2gAIAQEAAT8Q6vAzDg4+
Kt0R5Jz7zj3hsILdPW8kwPECL1Ao9TA8S8nRcHM98wB2dVHZPfMXDxNiA26lExEU
SAsyjcRs1NmbEKo5iOX4hlf3mOAepsREN4htmxCxY/SWpvXmbpHkhWk+0cZ7/fQl
wE0kbdoCN4iK3iCOzG3aQKn/2Q==
"/>
</svg>
```

##  `usvg --version`
0.27.0

## change
` xlink:href="data:image/jpeg;base64, /9j/` get replaced by ` xlink:href="data:image/jpg;base64, /9j/`

## MIME-type-definition
Accoring to Glrx on https://phabricator.wikimedia.org/T193929#4184557

> data: should be followed with a MIME type.
> 
> "image/jpg" is not a valid MIME type, so this is not a bug and can be closed.
> 
> "image/jpeg" is the appropriate MIME type.
> 
> see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
> 
> either the MIME type is given or it defaults to "text/plain..."
> 
> MIME type defined:
> https://www.iana.org/assignments/media-types/media-types.xhtml
> does not define JPEG but links to
> https://tools.ietf.org/html/rfc2046
> which uses "image/jpeg"

PS: Wikimedia still uses `c-librsvg 2.40.x` from 2017.

## Copyleft

source: https://github.com/RazrFalcon/resvg/blob/master/tests/svg/e-image-009.svg

license: MIT The library itself is under the MPL2.0, but tests are under MIT, so you can do whatever you want with them.

author: https://github.com/RazrFalcon (assuming)

**Comment by RazrFalcon** [comment] 2023-01-10 18:50
Makes sense. Will fix.

**Comment by flxzt** [comment] 2023-02-23 15:11
I would have a fix, would it make sense to make a `v0.27.1` fix release? Since `v0.27` it is the last version where Svg export is possible.

**Comment by RazrFalcon** [comment] 2023-02-23 17:47
`usvg` CLI is dead. So no. It's out of scope. Sorry. I have no time working on it.

**Closed by RazrFalcon** 2023-02-23 17:47 UTC

**Comment by RazrFalcon** [comment] 2023-02-23 17:58
It shouldn't be that hard to fork `usvg` CLI (under a new name) to reproduce older behavior. Which is what you should probably do.

**Comment by flxzt** [comment] 2023-02-23 18:01
Oh personally I'm not using the CLI, I am using the `Tree::to_string()` API

**Comment by RazrFalcon** [comment] 2023-02-23 18:12
`Tree::to_string()` exists just for CLI, so for me they are the same.

Then it should be even easier. Just copy-paste the old `export.rs` code and not forget to call `tree.convert_text(&fontdb);` beforehand. And you will get the output you want.

Because usvg no longer converts text-to-paths there is no way to implement `Tree::to_string`. Writing `text` elements would be an insane challenge. I just have no time dealing with it.

And `usvg` becomes less and less _simplifying_ lately, due to SVG 2 stuff. I would probably have to remove markers flattening as well...

I do plan to write a separate project like an original `usvg`, that would produce the simplest possible SVG, not lossless, but it would take months and I don't have any free time.

**Comment by flxzt** [comment] 2023-02-24 11:11
Thanks for the pointers, that sounds like a good way forward. For refence, I did exactly that, and ported `export.rs` to usvg `0.29`. The source is here (for now): https://github.com/flxzt/rnote/blob/main/rnote-engine/src/usvg_export.rs

**Comment by RazrFalcon** [comment] 2023-03-25 15:41
Fixed.
