### ISSUE TITLE
An SVG renders as empty canvas above a particular resolution

### ISSUE THREAD

**Issue by nikarh** [RazrFalcon/resvg#612] opened 2023-04-12 09:51 UTC
Hi,

I have an example SVG, which renders just fine at resolution `8191x6301`, but one pixel above in any dimension (e.g. `8192x6302`) renders it as a transparent canvas.

This is reproducible with rust code and a CLI tool on the current master.

```
resvg -w 8191 -h 6301 example.svg example0.png
resvg -w 8192 -h 6302 example.svg example1.png
```

[example.svg](https://user-images.githubusercontent.com/5517011/231421938-b3e442e7-73f0-46ba-998d-040f3bd57d92.svg)

**Comment by RazrFalcon** [comment] 2023-04-12 10:09
Duplicate of #570

**Closed by RazrFalcon** 2023-04-12 10:09 UTC

**Comment by RazrFalcon** [comment] 2023-04-22 10:19
Fixed.
