### ISSUE TITLE
pattern not rendered on small scalles (large viewBox)

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#366] opened 2021-03-30 19:27 UTC
Same file as in https://github.com/RazrFalcon/resvg/issues/255#issue-573041445 , but new issue.

## not rendered
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg height="200mm" viewBox="0,0,708.66,708.66" width="200mm" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <pattern id="a" height="1.42" patternTransform="translate(174.33 157.23)" patternUnits="userSpaceOnUse" width="2.83">
  <path d="m0 1.4173h1.5945v-.0886h-1.5945zm1.4173-.62v-.1772h1.4173v.1772zm-1.4173 0h.1772v-.1772h-.1772zm0-.7087v-.0886h1.5945v.0886z" fill="#3fbfff" fill-rule="evenodd"/>
 </pattern>
 <path d="m52.625 261.6114-.425.5-.55.3-.725.95-.375 1.05-1 .65-2.6 3-.325.875-1.3 1.525-.525.1-.375-.125-.45-.15-.45.425-.35 1.125.025.7.25.875.875 1.025 1.05.725 1.3.8.5.675.475 1.2.9 1.125 1.8 1.675 2.375 1.975 1.025 1.45.75.675.925.2.7.275.375.4.05.325-.225.25-.8.05-.425.175-.4.1-.325-.025-.525-.225-.45.25-.775.125-.525-.4-.325-.725-.175-.925-.125-.95-.6-.825-.725-.375-1.2-1.075-1.575-1.825-2.1-3.175-1.35-.85-.675-.1-.3.325-.25 1.025-.175 2.825-.3 1.05.175.575.45.5.75.4 1.225.45.45.475.15.55-.3.675-.925 1.675-1.15 1.225-1.25.6-.6.375-.4 1.125-.6 1.85-.15.475-.55.525-.2.95-.375.625-.225 1.075.2.9.5 1.2.55.1.975.475 1.575.425 1.2.1.925-.25 2.225-.05 1.1.05.5.1.625-.025.475-.2.675.025.475.275 1.075.95.55.425 1.175 1.375 1.125 1 1.825.5 1.975.175.45.45.025.725-.375.8-.925 1.1-.9.6-.35.75-.325.8.05.525.4.275h.4l2.6-1.5 2.725-1.8 1.1-1.125 1.95-1.35 3.05-1.4.85-.2 1.35.125 1.3.2 3.35-.075.725-.175 1.325-.875 1-1.125.025-1.225-1.025-1.55-1.1-1.625-.625-.575-.35-.55.075-2.675-.225-1.375-.875-1.425-1.925-.825-1.275-.25-1.9-1.15-.55-.8-.625-2.1-.25-1.825.2-1.475.2-1.225-.125-2-.425-.15h-.4l-1.225-.625-1-.225-1 .225-.725.6-.325.45-.925.35-.875.925-.475.2-.775-.05-1.025.725-.9.325-.675-.05-.825.1-1.025-.5-.925-.25-1.275-1.425-.675-1.6-.075-2 .575-1.825.65-.775.525-.575-.025-.575-.575-2.3-.3-.975.125-1.65.2-.8-.075-1.4-.325-.75z" fill="url(#a)" fill-rule="evenodd"/>
 <path d="m83.3125 299.8177.125 1.7188-.4375 1.5313-.2813.9063-.1563.7188.0313.875.3125 1.0625.6563 1.4375.375.75.9063 3.0625.375 1.8125.0313.875.4063.875.4688 1.125.0312.5625-.2188.5625-.3125.5938-.0313.2188.0313.3125.4375.375.1875.6563-.2188.6875-.2813.625-.9375.3438-.9063.125-.5625-.3438-.5313-.5313-1.0938-.5h-.75l-.75.2188-.5938.5-.875.2188-.5.4063-.25.0625-1.5938.8438-1.1563.4063-.75.2813-.9063.8438-1.5625 1-1 1-2 1.4375-1 .5625-1.1563.375-1.125.5313-1.4063.5313-.5313.0312-.5313.2188-.4375.6563-.8438.5-1.2188.0312-.4375.1563-.5938.1563-1.0313.4375-.7813.5313-1.125 1.5313-.9688 1-1.1563.5938-.9688.4375-.1875.6875.4063.5938-.0938 1.0938.0938.625.8438.5313 1.1875-.125.75-.7813.5-.0625.2188.4063-.0938.625-.5313.5938-.2188.5313-1 .7188-1.4375.7813h-.875l-.1875-.5938.0938-1.4375.0938-.8438-.2812-.6562-.375-.625.25-.4688-.1563-.5313-.125-.5313-.7813-.0312-.7188.2813-.5313.375-.1563.4375-.6875 1.1563-.5313.6875-.6875.375-1.0625.0937-1.75-.0937-1.8125.0937-1.75.5313-1.0938.3125-1.5313.75-1.0313 1.1875-1.5938 1.1875-1.0625 1.375-1.4063 1.25-.9688.4375-.875.2188-.8438.25-1.2813.875-.9375.9688-.8474.3486-.1274-1.1919-.15-.35.025-.475.875-.85 1.45-1.15.425-.85-.35-1.05.6-.75-.05-1.675-.25-.5.175-1.525-.45-.325.125-.875.125-.25-.275-.675-.4-.25-.9-.575-.125-.65.275-.525.9-1.175 2.525-2.875.775-1.675.05-.85-.525-.775-1.2-1.1-.675-1v-.45l.475-.2.55.2.7.7.875 1.275.725.95.55.15.825-.3.425-.4.85-.275.95.225.775.475.325.4.7.2.725.5.85.4.325-.1v-.45l-.5-.8-1.125-.95-.875-.25-1.7-.325-2.625-.75-1.65-.425-.7-.55-.025-.45 1.4-1.725 1.3-1.9 1.475-1.325.85-.475 1.675-1.375 1.1-1.4 1.525-1.075.85-.475 1.825-.5 3.25-.9h1.675l2.65-.275 1.425-.225.375.05.175.25.05.35-.2.25.15.15.8.075.775-.4 1.375-.875.875-.15 1.65.125.775.4.925.325 1.525-.05.9-.325.6-.375.6-.675.725-.275 1.525.025 1.525.275 1.425-.1.675-.35-.025-.95.6-1.175.825-.35.525-.475.1-.9.375-.875.625-.675 1.05-.4 1.325-.375 1.65-.725 1.3-1 .95-1.3.9-1.575.5-1.2.075-1.475-.0626-1.4846zm-74.8125 56.125-.4375-3.2813-.5625-1.8125-.5625-1.3438v-2.7501l.5313-.8125.7188-1.5313-.4688-1.0625-.1563-1.2813.5-.9688 1-.625 1.0313-1.375 1.875-1.0625 1.6875-.7188.5625.1563.5625.5938.3125.5625 1.375-.0625 1.25-.8125.8125-1 1.3438-2.25.5625-.3438.4063-.4688.4688-1.1563 1-1.125 1.1875-.8438.5625-.7813.4943-.0952-.2491 1.6438-.3889 1.149-.0884 1.3435v1.644l.1768.4596.1768.1061.1237-.8662.2828-1.6971.5127-1.8208.6894-1.6617.4773-1.7147.5127-1.5026.495-.8309.3536-.3182.3359.0354.2828.3005.0177 1.2728-.3359 2.1744-.1414 1.4496-.0177.7425-.4419 1.0607-.0707.5834-.6718 1.0607-.7248 1.3965-.4773 1.2728-.1591 2.3865-.1414.6894v3.1113l.3889.6364.3005 1.043-.053 1.9799-.4066.6364-.6541.601-1.2374.495-1.3435.4419-1.2374.1768-.8485 1.2198-.601.8839-1.5181 1.8613-2.2 2.825-1.875 2.45-2.05 2-.85.575-.8.025-.4-.4-.05-1.275.3-1.85v-.475l-.35-.55-.25-.075-.175.7v.55l-.2552.2175zm33.1318-70.3152-.7425.8242-1.1932.5347-1.4496.2386-.9104.3933-.5259.7734-1.0474.1856-.738-.1414-.9668.2273.644-.6876.5524-.1436.8507.0332.4419-.0663.3646-.2541.5414-.5856 1.4584-.6187 1.2264-.4972.3977.0111.3315-.3535v-.3757l.453-.3867.5547-.2273zm-2.3818 13.5963-.2344.2813-.375.2969-.7188.4844-.5469.2969-.4219.0156-.2188-.0625-.25-.375-.2188-.1719-.1094-.2344-.1875-.2656-.25-.0781v-.2031l.3125-.125-.0938-.2656-.5469-.0781-.3903.1405-.6094-.125-.5625-.125-.5156.0469-.25.2656-.375.2813v.3438h-.25l-.5-.0781-.4063.125-.3906-.0312-.1406-.2814-.2188-.1875-.0625-.2813-.2344-.125-.5.2344-.1406.2031-.1406.25.0781.2656-.0781.1875-.3594.0312-.2969.1094-.2031.4375-.4844.2344-.7656-.1719-.25-.2344-.4062-.1074.3223-.438.0177-.6541-.2652-.5303v-.3535l.7601-.7248.2652.0884.3005.5657.3182.0884.1414-.3182.1591-2.0153.2298-.9369.6541-.6187 2.192-.7071 1.096-.1061.8662-.2121 1.6971-.5303 1.1844-.6718.6541-.601.4419-.7778.7425-.8662.5657-.3535.3182.0884.0177.7248-.5834 1.1844-.9016 1.8031-.4419.4419-.053.7955.3005.6718.0177 1.5733.1414.6187.1945.1237.7778 1.1314.5091.3469zm-26.3974-14.2571.1237-.2298.4243-.1768-.1061-.9016-.4066-.7425-.548-.5834-.2828-.1237-.0884-.3536-.4243-.601-.3359-.1237-.2121-.1945-.3182-.7601-.2652-.3182.0707-.4066.1247-.2109-1.5459-.4227-.9375.0312-1.2031.25-1.1563-.0625-.5313-.25-.1875-.1094-.3125.0312-.2344.2188-.0781.1875-.2656.2188-.3906-.1094-.3281-.1719-.2656-.2188-.1094-.1563-.1719-.1094-.1406-.0156-.1719.125.7188 1.2031.3438.3594.3594.25.8906.5469.5469.1563.4375.4375.5625.6406.4219.25.5938.0625.5938.3906.1875.3125.1563.1875.375.0625.3438.0156.3125.0781.3125.0156.3594.1094.2344.2344.3594.0937.3281.2031.2969.2188.4219.2031.3594-.0312.2031.125.2188.2813.4647.3805zm13.9653 9.2454.0354 1.5203-.5657 1.2551-1.043 1.3435-.3889.3889.1061.1591 1.043-.0354.3359-.2121.2298.3005v.4773l-.1591.5657.0474.2482-.49.3445-1-.0156-.5781.4063-.7031.4219-.4375.1094-.2344-.0937-.3125-.5781-.0469-.5938-.2031-.2813-.0938-.4375.2188-.375.375-.5313.7344-.4219.625-.25.4063-.3125.125-.375.4063-.0937h.5469l.2344-.3594.4375-1.2188.0781-1.0781-.4946-2.005z" fill="url(#a)" fill-rule="evenodd"/>
</svg>
```
 
![all](https://user-images.githubusercontent.com/15687581/113044886-7349aa80-919e-11eb-801c-532f199a5f63.png)

## rendered on small viewBox

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg height="28.05mm" viewBox="0,0,83.672,99.4" width="23.61mm" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <pattern id="a" patternTransform="translate(171.75 -104.38)" xlink:href="#c"/>
 <pattern id="b" patternTransform="translate(171.75 -104.38)" xlink:href="#c"/>
 <pattern id="c" height="1.42" patternTransform="translate(174.33 157.23)" patternUnits="userSpaceOnUse" width="2.83">
  <path d="m0 1.4173h1.5945v-.0886h-1.5945zm1.4173-.62v-.1772h1.4173v.1772zm-1.4173 0h.1772v-.1772h-.1772zm0-.7087v-.0886h1.5945v.0886z" fill="#3fbfff" fill-rule="evenodd"/>
 </pattern>
 <path d="m50.047 0-.425.5-.55.3-.725.95-.375 1.05-1 .65-2.6 3-.325.875-1.3 1.525-.525.1-.825-.275-.45.425-.35 1.125.025.7.25.875.875 1.025 1.05.725 1.3.8.5.675.475 1.2.9 1.125 1.8 1.675 2.375 1.975 1.025 1.45.75.675.925.2.7.275.375.4.05.325-.225.25-.8.05-.425.175-.4.1-.325-.025-.525-.225-.45.25-.775.125-.525-.4-.325-.725-.175-.925-.125-.95-.6-.825-.725-.375-1.2-1.075-1.575-1.825-2.1-3.175-1.35-.85-.675-.1-.3.325-.25 1.025-.175 2.825-.3 1.05.175.575.45.5.75.4 1.225.45.45.475.15.55-.3.675-.925 1.675-1.15 1.225-1.25.6-.6.375-.4 1.125-.6 1.85-.15.475-.55.525-.2.95-.375.625-.225 1.075.2.9.5 1.2.55.1.975.475 1.575.425 1.2.1.925-.25 2.225-.05 1.1.05.5.1.625-.025.475-.2.675.025.475.275 1.075.95.55.425 1.175 1.375 1.125 1 1.825.5 1.975.175.45.45.025.725-.375.8-.925 1.1-.9.6-.35.75-.325.8.05.525.4.275h.4l2.6-1.5 2.725-1.8 1.1-1.125 1.95-1.35 3.05-1.4.85-.2 1.35.125 1.3.2 3.35-.075.725-.175 1.325-.875 1-1.125.025-1.225-1.025-1.55-1.1-1.625-.625-.575-.35-.55.075-2.675-.225-1.375-.875-1.425-1.925-.825-1.275-.25-1.9-1.15-.55-.8-.625-2.1-.25-1.825.2-1.475.2-1.225-.125-2-.425-.15h-.4l-1.225-.625-1-.225-1 .225-.725.6-.325.45-.925.35-.875.925-.475.2-.775-.05-1.025.725-.9.325-.675-.05-.825.1-1.025-.5-.925-.25-1.275-1.425-.675-1.6-.075-2 .575-1.825.65-.775.525-.575-.025-.575-.575-2.3-.3-.975.125-1.65.2-.8-.075-1.4-.325-.75z" fill="url(#b)" fill-rule="evenodd"/>
 <path d="m80.734 38.206.125 1.7188-.4375 1.5313-.2813.9063-.1563.7188.0313.875.3125 1.0625.6563 1.4375.375.75.9063 3.0625.375 1.8125.0313.875.4063.875.4688 1.125.0312.5625-.2188.5625-.3125.5938-.0313.2188.0313.3125.4375.375.1875.6563-.2188.6875-.2813.625-.9375.3438-.9063.125-.5625-.3438-.5313-.5313-1.0938-.5h-.75l-.75.2188-.5938.5-.875.2188-.5.4063-.25.0625-1.5938.8438-1.1563.4063-.75.2813-.9063.8438-1.5625 1-1 1-2 1.4375-1 .5625-1.1563.375-1.125.5313-1.4063.5313-.5313.0312-.5313.2188-.4375.6563-.8438.5-1.2188.0312-.4375.1563-.5938.1563-1.0313.4375-.7813.5313-1.125 1.5313-.9688 1-1.1563.5938-.9688.4375-.1875.6875.4063.5938-.0938 1.0938.0938.625.8438.5313 1.1875-.125.75-.7813.5-.0625.2188.4063-.0938.625-.5313.5938-.2188.5313-1 .7188-1.4375.7813h-.875l-.1875-.5938.0938-1.4375.0938-.8438-.2812-.6562-.375-.625.25-.4688-.1563-.5313-.125-.5313-.7813-.0312-.7188.2813-.5313.375-.1563.4375-.6875 1.1563-.5313.6875-.6875.375-1.0625.0937-1.75-.0937-1.8125.0937-1.75.5313-1.0938.3125-1.5313.75-1.0313 1.1875-1.5938 1.1875-1.0625 1.375-1.4063 1.25-.9688.4375-.875.2188-.8438.25-1.2813.875-.9375.9688-.8474.3486-.1274-1.1919-.15-.35.025-.475.875-.85 1.45-1.15.425-.85-.35-1.05.6-.75-.05-1.675-.25-.5.175-1.525-.45-.325.125-.875.125-.25-.275-.675-.4-.25-.9-.575-.125-.65.275-.525.9-1.175 2.525-2.875.775-1.675.05-.85-.525-.775-1.2-1.1-.675-1v-.45l.475-.2.55.2.7.7.875 1.275.725.95.55.15.825-.3.425-.4.85-.275.95.225.775.475.325.4.7.2.725.5.85.4.325-.1v-.45l-.5-.8-1.125-.95-.875-.25-1.7-.325-2.625-.75-1.65-.425-.7-.55-.025-.45 1.4-1.725 1.3-1.9 1.475-1.325.85-.475 1.675-1.375 1.1-1.4 1.525-1.075.85-.475 1.825-.5 3.25-.9h1.675l2.65-.275 1.425-.225.375.05.175.25.05.35-.2.25.15.15.8.075.775-.4 1.375-.875.875-.15 1.65.125.775.4.925.325 1.525-.05.9-.325.6-.375.6-.675.725-.275 1.525.025 1.525.275 1.425-.1.675-.35-.025-.95.6-1.175.825-.35.525-.475.1-.9.375-.875.625-.675 1.05-.4 1.325-.375 1.65-.725 1.3-1 .95-1.3.9-1.575.5-1.2.075-1.475-.0626-1.4846zm-74.812 56.125-.4375-3.2813-.5625-1.8125-.5625-1.3438v-2.7501l.5313-.8125.7188-1.5313-.4688-1.0625-.1563-1.2813.5-.9688 1-.625 1.0313-1.375 1.875-1.0625 1.6875-.7188.5625.1563.5625.5938.3125.5625 1.375-.0625 1.25-.8125.8125-1 1.3438-2.25.5625-.3438.4063-.4688.4688-1.1563 1-1.125 1.1875-.8438.5625-.7813.4943-.0952-.2491 1.6438-.3889 1.149-.0884 1.3435v1.644l.1768.4596.1768.1061.1237-.8662.2828-1.6971.5127-1.8208.6894-1.6617.4773-1.7147.5127-1.5026.495-.8309.3536-.3182.3359.0354.2828.3005.0177 1.2728-.3359 2.1744-.1414 1.4496-.0177.7425-.4419 1.0607-.0707.5834-.6718 1.0607-.7248 1.3965-.4773 1.2728-.1591 2.3865-.1414.6894v3.1113l.3889.6364.3005 1.043-.053 1.9799-.4066.6364-.6541.601-1.2374.495-1.3435.4419-1.2374.1768-.8485 1.2198-.601.8839-1.5181 1.8613-2.2 2.825-1.875 2.45-2.05 2-.85.575-.8.025-.4-.4-.05-1.275.3-1.85v-.475l-.35-.55-.25-.075-.175.7v.55l-.2552.2175zm33.132-70.315-.7425.8242-1.1932.5347-1.4496.2386-.9104.3933-.5259.7734-1.0474.1856-.738-.1414-.9668.2273.644-.6876.5524-.1436.8507.0332.4419-.0663.3646-.2541.5414-.5856 1.4584-.6187 1.2264-.4972.3977.0111.3315-.3535v-.3757l.453-.3867.5547-.2273zm-2.3818 13.596-.2344.2813-.375.2969-.7188.4844-.5469.2969-.4219.0156-.2188-.0625-.25-.375-.2188-.1719-.1094-.2344-.1875-.2656-.25-.0781v-.2031l.3125-.125-.0938-.2656-.5469-.0781-.3903.1405-.6094-.125-.5625-.125-.5156.0469-.25.2656-.375.2813v.3438h-.25l-.5-.0781-.4063.125-.3906-.0312-.1406-.2814-.2188-.1875-.0625-.2813-.2344-.125-.5.2344-.1406.2031-.1406.25.0781.2656-.0781.1875-.3594.0312-.2969.1094-.2031.4375-.4844.2344-.7656-.1719-.25-.2344-.4062-.1074.3223-.438.0177-.6541-.2652-.5303v-.3535l.7601-.7248.2652.0884.3005.5657.3182.0884.1414-.3182.1591-2.0153.2298-.9369.6541-.6187 2.192-.7071 1.096-.1061.8662-.2121 1.6971-.5303 1.1844-.6718.6541-.601.4419-.7778.7425-.8662.5657-.3535.3182.0884.0177.7248-.5834 1.1844-.9016 1.8031-.4419.4419-.053.7955.3005.6718.0177 1.5733.1414.6187.1945.1237.7778 1.1314.5091.3469zm-26.397-14.257.1237-.2298.4243-.1768-.1061-.9016-.4066-.7425-.548-.5834-.2828-.1237-.0884-.3536-.4243-.601-.3359-.1237-.2121-.1945-.3182-.7601-.2652-.3182.0707-.4066.1247-.2109-1.5459-.4227-.9375.0312-1.2031.25-1.1563-.0625-.5313-.25-.1875-.1094-.3125.0312-.2344.2188-.0781.1875-.2656.2188-.3906-.1094-.3281-.1719-.2656-.2188-.1094-.1563-.1719-.1094-.1406-.0156-.1719.125.7188 1.2031.3438.3594.3594.25.8906.5469.5469.1563.4375.4375.5625.6406.4219.25.5938.0625.5938.3906.1875.3125.1563.1875.375.0625.3438.0156.3125.0781.3125.0156.3594.1094.2344.2344.3594.0937.3281.2031.2969.2188.4219.2031.3594-.0312.2031.125.2188.2813.4647.3805zm13.965 9.2454.0354 1.5203-.5657 1.2551-1.043 1.3435-.3889.3889.1061.1591 1.043-.0354.3359-.2121.2298.3005v.4773l-.1591.5657.0474.2482-.49.3445-1-.0156-.5781.4063-.7031.4219-.4375.1094-.2344-.0937-.3125-.5781-.0469-.5938-.2031-.2813-.0938-.4375.2188-.375.375-.5313.7344-.4219.625-.25.4063-.3125.125-.375.4063-.0937h.5469l.2344-.3594.4375-1.2188.0781-1.0781-.4946-2.005z" fill="url(#a)" fill-rule="evenodd"/>
</svg>
```

![detail](https://user-images.githubusercontent.com/15687581/113044966-907e7900-919e-11eb-8703-01b6f259678c.png)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Hidrograf%C3%ADa_Galicia_Cunca_Mari%C3%B1a_Oriental_en.svg

author Iago Casabiell González

license https://creativecommons.org/licenses/by-sa/4.0/deed.de

**Comment by RazrFalcon** [comment] 2021-05-23 16:02
Duplicate of #385

**Closed by RazrFalcon** 2021-05-23 16:02 UTC
