### ISSUE TITLE
usvg argument parsing broken in 0.14

### ISSUE THREAD

**Issue by ijackson** [RazrFalcon/resvg#374] opened 2021-04-14 17:13 UTC
With git head `09d6cde`:
```
rustcargo@zealot:~/Rustup/Game/resvg$ target/debug/usvg --version
Error: free-standing argument is missing.
rustcargo@zealot:~/Rustup/Game/resvg$ target/debug/usvg --help
Error: free-standing argument is missing.
```

Previously:
```
rustcargo@zealot:~/Rustup/Game/resvg$ target/debug/usvg --version
0.13.1
rustcargo@zealot:~/Rustup/Game/resvg$ usvg --help
usvg (micro SVG) is an SVG simplification tool.
[...]
```

Bisecting fingered `b2da26d40a59813e82b0fb2ef1df6b8b7977825c` "Update pico-args.".  I looked at the changelog for pico-args and nothing jumped out but I haven't looked at the code in usvg.

I checked `resvg/CHANGELOG.md` and didn't see any mention of this so I think it must not be deliberate...

Thanks.

**Comment by RazrFalcon** [comment] 2021-04-14 17:29
Duplicate of #360

**Comment by RazrFalcon** [comment] 2021-04-14 17:29
Will try to fix it soon.

**Closed by RazrFalcon** 2021-04-14 17:29 UTC
