### ISSUE TITLE
malformation

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#263] opened 2020-03-03 20:58 UTC
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/2/21/Metastasis_sites_for_common_cancers-IT.svg)
|ink|![Metastasis sites for common cancers-IT](https://user-images.githubusercontent.com/15687581/75818705-a81be000-5d99-11ea-9dfe-837be0ff3ad8.png)
|resvg|![Metastasis sites for common cancers-IT_resvg](https://user-images.githubusercontent.com/15687581/75818711-ac47fd80-5d99-11ea-9f8d-d46411f2e5a3.png)
|rsvg|![Metastasis sites for common cancers-IT_rsvg](https://user-images.githubusercontent.com/15687581/75818724-b1a54800-5d99-11ea-9030-f49caf7a8d9a.png)

![Screenshot from 2020-03-03 21-55-00](https://user-images.githubusercontent.com/15687581/75818750-bf5acd80-5d99-11ea-98f5-e2ba07f7c9dc.png)

#### What should have happened?
 - head/stomage missing
 - arrow-color

#### Copyright

source https://commons.wikimedia.org/wiki/File:Metastasis_sites_for_common_cancers-IT.svg

author Mikael Häggström
    abgeleitetes Werk Adert

license https://creativecommons.org/publicdomain/zero/1.0/deed.de

#### Version and Operating System:

- Inkscape Version: 0.92.4 or 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment] 2020-03-24 17:17
Duplicate of #235

**Closed by RazrFalcon** 2020-03-24 17:17 UTC
