### ISSUE TITLE
Text is not scaled properly in SVG

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg#694] opened 2024-01-10 07:17 UTC
The following SVG: 
```svg
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="38px" height="21px" viewBox="0 0 38 21" style="background-color: #ffffffff" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" >
    <text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 2.9617 17.9917)" style="font:normal normal normal 200px 'Arial'" >
        H</text>
    <text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 15.1108 10.8167)" style="font:normal normal normal 200px 'Arial'" >
        O</text>
    <text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 27.8166 17.9917)" style="font:normal normal normal 200px 'Arial'" >
        H</text>
    <path stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 -1096 -385)" d="M 22208,7893.05 L 22214,7903.44 L 22156.2,7936.83 L 22150.2,7926.44 L 22208,7893.05 Z " />
    <path stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 -1096 -385)" d="M 22449.5,7926.25 L 22443.5,7936.65 L 22385.8,7903.33 L 22391.8,7892.94 L 22449.5,7926.25 Z " />
</svg>
```

is not rendered properly by resvg:
<img width="1502" alt="image" src="https://github.com/RazrFalcon/resvg/assets/47084093/9893a098-1708-460c-94b6-d78f7cb12ea9">

I presume it's because the font property in CSS is currently not supported?

Originally reported here: https://github.com/typst/typst/issues/3162

**Comment by RazrFalcon** [comment] 2024-01-10 12:46
I guess this is #431

**Comment by LaurenzV** [comment] 2024-01-10 13:33
That's probably it, indeed. Will see if I can implement it once I find some time.

**Comment by RazrFalcon** [comment] 2024-01-10 15:02
Duplicate of https://github.com/RazrFalcon/resvg/issues/431

**Closed by RazrFalcon** 2024-01-10 15:02 UTC
