### ISSUE TITLE
Benchmark on something other than icons

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/resvg#185] opened 2019-11-02 20:36 UTC
Benchmarking on icons only is not particularly representative of performance in general.

I've tried rendering [Inkscape about screens](https://inkscape.org/*inkscape-vectors/galleries/about-screens/?page=1&) as they're bigger than icons and represent a wide variety of SVG feature combinations, using more advanced features over time as Inkscape itself evolved.

On my machine resvg takes 1 second to render them all while librsvg takes 5 seconds. I've blacklisted 0.48 splash screen as it has some unsupported filters. librsvg also renders the 0.92 splash screen incorrectly, while resvg works fine.

**Comment by RazrFalcon** [comment] 2019-11-02 20:44
Yes, I thought about it. The problem is to have an archive of such images that an end user can download and test by itself. That's why I'm using icon packs.

On the other hand, we can simply render Oxygen Icons (which are very complex) to 1024x1024 or something like this.

**Comment by Shnatsel** [comment] 2019-11-02 20:52
Most Inkscape about screens are under permissive licenses (at least they're listed as such on the website), so we could just download them one by one and then put an archive with them in github releases.

**Comment by Shnatsel** [comment] 2019-11-02 20:54
What I've linked above is just the about screens that have actually been used, for extra variety we could look at [all contest submissions](https://inkscape.org/*inkscape-vectors/galleries/).

**Comment by RazrFalcon** [comment] 2019-11-02 21:01
I don't want to include any images in the repo, so it will be better to create a separate repo with all of these images.

**Comment by Shnatsel** [comment] 2019-11-02 21:02
Many Linux distros ship dumps of openclipart.org - see e.g. https://packages.ubuntu.com/xenial/openclipart Ubuntu package. There are direct download links for the archives, it's 174Mb of SVG when unpacked.

**Comment by RazrFalcon** [comment] 2019-11-02 21:04
Yes, I have that one, but those images are mostly very simple. Just shapes and curves.

**Comment by Shnatsel** [comment] 2019-11-02 21:27
Yeah, but it is one of the use cases for SVG, and it's important to know that we don't regress on that one. By the way - on that Ubuntu package resvg takes 2m40s, librsvg 7m50s

**Comment by RazrFalcon** [comment] 2019-11-02 21:35
Performance is not the current priority. And I'm not using those performance measures for regression testing. I have `/benches` for this now. And this should be enough, since `resvg` uses a very limited set of features. Just path rendering with color, gradient, pattern, clipping, masking and filters.

`librsvg` in your tests is surprisingly slow. They should be on par.

**Comment by Shnatsel** [comment] 2019-11-02 21:39
I'm comparing resvg 0.7.0 with Cairo backend against rsvg-convert version 2.40.20, this version predates the Rust conversion. Outdated version might be the reason why it's so slow.

**Comment by RazrFalcon** [comment] 2019-11-03 12:23
Yes, you should you the latest one.

**Comment by RazrFalcon** [comment] 2019-12-19 15:08
I will close this because I've removed comparison with other libraries completely since it was useless.

**Closed by RazrFalcon** 2019-12-19 15:08 UTC

**Comment by Shnatsel** [comment] 2019-12-19 17:32
I feel it was important to show that it performance is at least in the same ballpark as other libraries, so it's not entirely useless.

**Comment by RazrFalcon** [comment] 2019-12-19 17:36
The point is that's not possible. You can construct a file that will perform better using a specific library. 

Also, comparing just with librsvg and Qt is useless.

**Comment by Shnatsel** [comment] 2019-12-19 18:00
Well, Chrome and Firefox do not fill the same use cases. Qt is too limited in SVG support. But Batik, librsvg and Inkscape all make for reasonable comparison points.

Inkscape would be disproportionately penalized for its long startup time when spawning a new process for every icon. To work around that Inkscape can be started in persistent mode using `inkscape --without-gui --shell`, here's a complete script to make it work: https://gist.github.com/lzubiaur/9074270
And I'm pretty sure something similar will also work for Batik, although it's going to be very slow anyway.

And sure, benchmarks are always arbitrary, but it's important to know that the library can be at least in the same ballpark as other libs in terms of performance. When I see benchmarks across various backends with no external reference points, I generally assume that performance is much worse than other libraries, otherwise a comparison with other libs would be included. For resvg this would be a missed opportunity, because resvg performance is actually comparable to other libs.

**Comment by RazrFalcon** [comment] 2019-12-19 18:05
The startup/warm-up time is yet another issue, yes. But you're missing the point. The problem is in supported features and the way they are implemented. It can drastically affect the results. For example, librsvg, Inkscape and Batik doesn't support proper clipping, so they always be faster.

**Comment by Shnatsel** [comment] 2019-12-19 18:12
My point is, 5-10% difference usually doesn't matter. What matters is that the performance is in the same order of magnitude, that's what should be advertised.

**Comment by RazrFalcon** [comment] 2019-12-19 18:14
>that's what should be advertised

This will be a false advertisement. And clipping in `resvg` is times slower that in other libraries.

**Comment by Shnatsel** [comment] 2019-12-19 18:25
Clipping is just one part of a much larger process and significant changes to its time do not necessarily dramatically affect the total export time. And other libraries have their own slow cases too, that do not necessarily show up on typical files (just like resvg clipping).

But I trust you know better than I do, so I'll drop the issue.
