### ISSUE TITLE
Support for color(display-p3)

### ISSUE THREAD

**Issue by restlessdesign** [RazrFalcon/resvg#830] opened 2024-10-10 14:56 UTC
When attempting to parse the following (using [svg2pdf](https://github.com/Savjee/svg2pdf/tree/master)):
![input](https://github.com/user-attachments/assets/c25ad21b-5875-4612-992f-67386d592a24)

The following errors are output for strokes and fills:

```
Warning (in usvg::parser::style:147): Failed to parse stroke value: 'color(display-p3 0.6863 0.6863 0.6863)'. Fallback to no stroke.
Warning (in usvg::parser::style:141): Failed to parse fill value: 'color(display-p3 0.6863 0.6863 0.6863)'. Fallback to black.
```

I’m having a hard time understanding if this is just a matter of adding support for display-p3 (in [`Color`](https://github.com/RazrFalcon/resvg/blob/master/crates/usvg/src/tree/mod.rs#L696) perhaps?) _or_ if the `color` attribute as a whole needs to be supported.

Could someone weigh in on the complexity of this request?

**Comment by RazrFalcon** [comment] 2024-10-10 16:05
Duplicate of #514

**Closed by RazrFalcon** 2024-10-10 16:05 UTC

**Comment by RazrFalcon** [comment] 2024-10-10 16:06
>Could someone weigh in on the complexity of this request?

Tons of work. No plans on implementing this feature any time soon. Unless someone would send a patch.

See #806 as well.
