### ISSUE TITLE
Unable to parse oklab colors

### ISSUE THREAD

**Issue by nixon-voxell** [RazrFalcon/resvg#803] opened 2024-08-13 11:32 UTC
I hit a warning while trying to parse an svg with "oklab" colors:
```
WARN usvg::parser::style: Failed to parse fill value: 'oklab(31.061% 0.00233 -0.00267)'. Fallback to black.
```

**Comment by RazrFalcon** [comment] 2024-08-13 11:48
CSS Color Module Level 4 is still a draft and not supported by `resvg`.

Duplicate of #514

**Closed by RazrFalcon** 2024-08-13 11:48 UTC
