### ISSUE TITLE
Inaccurate rgb values with alpha gradients on transparent background

### ISSUE THREAD

**Issue by ace24713** [RazrFalcon/resvg#677] opened 2023-10-31 11:19 UTC
Using the following svg
![bitmap](https://github.com/RazrFalcon/resvg/assets/753186/ad1d6519-e180-4516-9fcb-67143c20eced)
rendered to png using resvg via the following command on v0.36.0
`resvg.exe --width 256 bitmap.svg bitmap.png`
there is some unusual color banding happening near the transparent bit in the middle. If I open the png in an image editor (gimp) and then remove the alpha channel you can see the color is wrong. Since the gradient goes from 000040 opaque to 000040 transparent to 000040 opaque the resulting image _should_ just be a square of solid color 000040 blue, but it is not.
![bitmap_noalpha](https://github.com/RazrFalcon/resvg/assets/753186/33351190-9864-4ebf-817b-7704b289a72a)
The bright blue strip in the middle at the most transparent point is an obvious error, but inspecting with color picker shows that most of the image is not 000040 at all, and it's actually striped with various shades of blue. Towards the middle there are obvious stripes of dark-light-dark-light blue. Here's a zoom-in of that bit, it's noticeable to my eyes but rather subtle. 
![image](https://github.com/RazrFalcon/resvg/assets/753186/f6480925-c749-46fc-bd67-22e98c73e266)
I also tried with `--shape-rendering crispEdges` and the result was basically identical.

**Comment by RazrFalcon** [comment] 2023-10-31 14:38
>resulting image should just be a square of solid color 000040 blue, but it is not

Should it? I don't think the SVG spec requires it. `resvg` uses `tiny-skia`, which is a Skia port. And if Skia does the same - then it's out of scope. I will check Skia's output later.
Our you can try it yourself here: https://fiddle.skia.org/c/@skcanvas_paint

SVG in general isn't designed for reproducibility. A renderer has a lot of freedom about rendering.

**Comment by ace24713** [comment] 2023-10-31 20:20
Well I'm not exactly well versed in the svg spec but here's what I found:
https://www.w3.org/TR/SVG11/masking.html#SimpleAlphaBlending
The formula for alpha compositing is basically `result.rgb = (1 - element.a)*canvas.rgb + element.rgb` therefore if the canvas is black-transparent then the resulting pixel color should be strictly the element.rgb value. Computing the element.rgb value is dependent on the color-interpolation. There isn't a lot of documentation here, it just says it should use either linearRGB or sRGB, but neither of those state anything about the alpha value. But I don't think I'm being unreasonable assuming that interpolating between blue and blue should be blue.

Now is this a skia issue? Here's my working theory (with a grain of salt, I've only been staring at this for a few hours). The Skia canvas stores pixel rgb values with premultiplied alpha to speed up composting. Therefore when the final pixel color is blitted out to the png the rgb values need to be un-multiplied (divided) by the alpha value. For particularly small alpha values this results in information loss due to floating point limitations. So yes, I was able to reproduce the issue using the skia fiddle tool. **However** the Skia canvas does not have to use premultiplied alpha, that's merely the default.
https://api.skia.org/classSkBitmap.html#ad6fcf3397a96b20c6ed1f07609df0b05
Skia appears to support using unpremultiplied alpha storage on bitmaps via kUnpremul. I can't test this in the fiddle tool though as it doesn't seem there's an api to change the alpha storage on the canvas supplied to the draw function.

So I hope at least some of this information is useful.

> A renderer has a lot of freedom about rendering.

Well... yes. A bit of an aside, but I'm using the resulting png image as an input sampler texture in a graphics shader, so the rgba values in the image are not 1:1 with the rgba values displayed on screen. I need a higher degree of color accuracy than most, and I assumed having a computer do the painting for me would yield better results. So far resvg has had the most precise output of any renderer I've tried (kudos), so this feels in-line with the project ethos to me.

**Comment by RazrFalcon** [comment] 2023-11-01 10:10
>Now is this a skia issue?

Because Skia/tiny-skia is used for rendering. And the canvas is always premultiplied. `kUnpremul` can be used for storage, but not for blending operations.
Your issue has nothing to do with resvg/SVG itself.

For now, there is now way to fix your "issue". This is by design. If you need a higher precision, you should be using 16bit PNGs, which resvg/tiny-skia do not support yet. 

>But I don't think I'm being unreasonable assuming that interpolating between blue and blue should be blue.

Many operations in Skia/tiny-skia are done using normalized floats, aka 0...1. So an 8bit unpremultiplied color is converted into premultiplied float one, processed, and then converted back to unpremultiplied 8bit. I think you can imagine how "precise" it is. No to mention that SIMD operations have tendency to have a lower precision as well.

**Comment by RazrFalcon** [comment] 2023-11-06 10:20
Out of scope.

**Closed by RazrFalcon** 2023-11-06 10:20 UTC
