### ISSUE TITLE
writing-mode supported?

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#246] opened 2020-02-28 20:56 UTC
|lib|pic|
|--|--|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/0/07/History_of_the_Universe-zh-hant.svg)
|ink|![History of the Universe-zh-hant](https://user-images.githubusercontent.com/15687581/75586552-f9179580-5a74-11ea-865e-f4af43120506.png)
|resvg|![History of the Universe-zh-hant_resvg](https://user-images.githubusercontent.com/15687581/75586559-fddc4980-5a74-11ea-8acb-49c53186c331.png)
|rsvg|![History of the Universe-zh-hant_rsvg](https://user-images.githubusercontent.com/15687581/75586568-02086700-5a75-11ea-9df6-272ac415a57e.png)

source: https://commons.wikimedia.org/wiki/File:History_of_the_Universe-zh-hant.svg

author Einweichen

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

**Comment by RazrFalcon** [comment] 2020-02-29 01:24
Duplicate of #222

**Closed by RazrFalcon** 2020-02-29 01:24 UTC
