### ISSUE TITLE
render unspecific mimetype

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#271] opened 2020-03-06 17:44 UTC
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/0/06/Ways_of_St-2._James_in_Europe.svg)
|ink|![Ways of St-2  James in Europe](https://user-images.githubusercontent.com/15687581/76107745-9a549d80-5fd9-11ea-9987-620ef95f83e7.png)
|resvg|![Ways of St-2  James in Europe_re](https://user-images.githubusercontent.com/15687581/76107756-9e80bb00-5fd9-11ea-9403-c693eebd1709.png)
|batik|![Ways of St-2  James in Europe_batik](https://user-images.githubusercontent.com/15687581/76107822-beb07a00-5fd9-11ea-8c2c-026d17f53203.png)

![Screenshot from 2020-03-06 18-39-14](https://user-images.githubusercontent.com/15687581/76107863-d425a400-5fd9-11ea-8a48-1367ad5a4cf9.png)

#### What should have happened?
 - `/9j/4AAQSkZJRgABAgAAZABkAAD` should be treated as `xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD`

(FYI: data:image/png;base64 start with `iVBORw0KGgoAAAANSUhEUgAA` )

#### Version and Operating System:

- Inkscape Version: 0.92.4 or 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21 or 2.47.3
- Operating System: Ubuntu 18.04

#### Source
https://commons.wikimedia.org/wiki/File:Ways_of_St-2._James_in_Europe.svg

**Comment by RazrFalcon** [comment] 2020-03-06 17:50
Duplicate of #264

**Closed by RazrFalcon** 2020-03-06 17:50 UTC
