### ISSUE TITLE
 gradientTransform="scale(0)"

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#247] opened 2020-02-28 21:01 UTC
|lib|pic|
|--|--|
|svg|![svg](https://upload.wikimedia.org/wikipedia/commons/1/12/Identify_renderer.svg)
|ink|![Identify renderer](https://user-images.githubusercontent.com/15687581/75586947-b3a79800-5a75-11ea-8e9b-2a5e5a431768.png)
|resvg|![Identify renderer_resvg](https://user-images.githubusercontent.com/15687581/75586957-b7d3b580-5a75-11ea-899c-a6873553ca71.png)
|rsvg|![Identify renderer_rsvg](https://user-images.githubusercontent.com/15687581/75586967-bb673c80-5a75-11ea-8f09-1f19606617c6.png)

I assume Inkscape renders correct?

source https://commons.wikimedia.org/wiki/File:Identify_renderer.svg

author TilmannR

license Public Domain

**Comment by RazrFalcon** [comment] 2020-02-29 01:21
Duplicate of #251

**Closed by RazrFalcon** 2020-02-29 01:21 UTC
