### ISSUE TITLE
misplaced pattern-grid

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#395] opened 2021-06-15 20:21 UTC
I assume this issue might be a duplicate of #221  #392

The last vertical line should be at the right end of the horizontal lines

## Input 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="750" height="500" viewBox="-31.675 -134.3 249.14 164.7" xmlns="http://www.w3.org/2000/svg">
 <defs>
  <pattern id="a" x="0" y="0" width="11.73" height="220" patternUnits="userSpaceOnUse" patternTransform="matrix(1 0 0 -1 0 0)">
   <path fill="#000000" stroke="#000000" stroke-width="0.37" d="M 0 0 L 0 220"/>
  </pattern>
  <pattern id="b" x="0" y="0" width="156.42" height="10" patternUnits="userSpaceOnUse" patternTransform="matrix(1 0 0 -1 0 0)">
   <path fill="#000000" stroke="#000000" stroke-width="0.37" d="M 0 0 L 156.42 0"/>
  </pattern>
 </defs>
 <path fill="#ffffff" stroke="none" transform="matrix(0.1 0 0 0.1 0 0)" d="M -316.8 -1343 L 2174.6 -1343 L 2174.6 304 L -316.8 304 Z"/>
 <path fill="#000000" stroke="#000000" stroke-width="7.4" stroke-linecap="round" transform="matrix(0.1 0 0 0.1 0 0)" d="M 0 0 L 2110 0 M 0 0 L 0 -1100"/>
 <path fill="url(#a)" stroke="none" d="M 0.3 0 L 215.7 0 L 215.7 -110 L 0.3 -110 Z"/>
 <path fill="url(#b)" stroke="none" d="M 0 -0.3 L 211.2 -0.3 L 211.2 -112.5 L 0 -112.5 Z"/>
</svg>

```
![svg](https://gitlab.com/inkscape/inbox/uploads/89a45474de9a83d7687c8de796dc3827/2014_West_Africa_Ebola_Epidemic__New_Cases_per_WeekCiCkskCU.svg)

source: https://commons.wikimedia.org/wiki/File:2014_West_Africa_Ebola_Epidemic_-_New_Cases_per_Week.svg

## Output

![2014_West_Africa_Ebola_Epidemic__New_Cases_per_WeekCiCkskCU_re](https://user-images.githubusercontent.com/15687581/122109961-4496b400-ce1e-11eb-9d75-ab535f368d24.png)

**Comment by RazrFalcon** [comment] 2023-05-21 14:02
Duplicate of #628

**Closed by RazrFalcon** 2023-05-21 14:02 UTC
