### ISSUE TITLE
Gradient rendering and built-in PNG images issues

### ISSUE THREAD

**Issue by PlkMarudny** [RazrFalcon/resvg#547] opened 2022-10-18 06:00 UTC
I noticed some rendering issues with gradients/embedded PNG images (see screenshots below, ignore fonts differences). The SVG file comes exported from Adobe Illustrator, so it is rather messy in general.

viewsvg.exe:
![image](https://user-images.githubusercontent.com/4361591/196346723-41ee79d9-c301-42ce-886d-751b78a5f1ae.png)

Chrome:
![image](https://user-images.githubusercontent.com/4361591/196346856-5a6fe2d6-5bed-4904-a161-6c1d754acc27.png)

Inkscape:
![image](https://user-images.githubusercontent.com/4361591/196346984-283b67d0-6ec6-44c2-b69c-3468565383c2.png)

Firefox (also has problems):
![image](https://user-images.githubusercontent.com/4361591/196347232-f4d0493c-3eb3-4f66-995a-629441bf6390.png)

Affinity Designer (total disaster):
![image](https://user-images.githubusercontent.com/4361591/196347421-6bfa600e-b685-402e-a435-dd9c662b20fd.png)

**Comment by RazrFalcon** [comment] 2022-10-18 12:28
Hi! Can you provide the SVG file?

**Comment by PlkMarudny** [comment] 2022-10-18 12:39
Zip version:

[Chart_for_Investigation.zip](https://github.com/RazrFalcon/resvg/files/9810415/Chart_for_Investigation.zip)

**Comment by RazrFalcon** [comment] 2022-10-18 13:15
Looks like #421 to me. `mix-blend-mode` isn't supported yet. For now, try exporting to SVG 1 and not SVG 2.

**Comment by RazrFalcon** [comment] 2022-10-22 16:27
Duplicate of #421

**Closed by RazrFalcon** 2022-10-22 16:27 UTC

**Comment by RazrFalcon** [comment] 2022-11-20 11:25
Should be fixed now.

**Comment by PlkMarudny** [comment] 2022-11-21 11:30
And it is, that's absolutely amazing, thank you.
