### ISSUE TITLE
<text> font style parsing error when use shorthand properties

### ISSUE THREAD

**Issue by MrThanlon** [RazrFalcon/resvg#599] opened 2023-03-21 06:42 UTC
input svg:
```svg
<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
  <style>
    .Rrrrr {
      font: italic 40px serif;
      fill: red;
    }
  </style>
  <text x="65" y="55" class="Rrrrr">Grumpy!</text>
</svg>
```
got:
```rust
font: Font {
    families: [
        "Times New Roman",
    ],
    style: Normal,
    stretch: Normal,
    weight: 400,
},
```
expected:
```rust
font: Font {
    families: [
        "serif",
    ],
    style: Italic,
    stretch: Normal,
    weight: 400,
},
```

**Comment by RazrFalcon** [comment] 2023-03-21 10:25
Duplicate of #431

**Closed by RazrFalcon** 2023-03-21 10:25 UTC
