### ISSUE TITLE
Invalid pattern offset

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#221] opened 2020-02-21 22:11 UTC
https://commons.wikimedia.org/wiki/File:Subglacial_Eruption-numbers.svg

|rsvg|resvg|
|---|---|
|![Subglacial Eruption-numbers_r](https://user-images.githubusercontent.com/15687581/75075817-f231d580-54fe-11ea-8437-ede8352cd398.png)|![Subglacial Eruption-numbers_re](https://user-images.githubusercontent.com/15687581/75075831-f827b680-54fe-11ea-8cad-82a46b421148.png)|

The stone labeled with 6 are higher in rsvg than in resvg maybe nummeric issues? (don't know which one is correct)

PS same for https://commons.wikimedia.org/wiki/File:Submarine_Eruption-numbers.svg

### Copyright

source https://commons.wikimedia.org/wiki/File:Subglacial_Eruption-numbers.svg

author Sémhur

license https://creativecommons.org/licenses/by-sa/4.0

**Comment by RazrFalcon** [comment] 2020-02-21 22:22
Yes, the pattern is a bit off.

**Comment by neinseg** [comment] 2021-06-04 14:02
I can confirm this. I'm running resvg v0.14.1. Several testcases are attached below.

When you flick between these testcases you will also notice that scale seems to be off as well.

Attached are three test cases:
* resvg output
* rsvg-convert output.
* output of [`gerbolyze/svg-flatten`](https://github.com/jaseg/gerbolyze)` | resvg`

gerbolyze is the svg-to-svg converter that I'm working on atm. It processes patterns down to individual `<path>`s.

Note that gerbolyze and rsvg-convert both agree very well, with resvg being the odd one out. BTW, while it may be legal by spec I think it would be great if resvg could try harder to produce less of a blurry mess for small patterns.

Here are the input SVG files (as zip to make github happy): [resvg-testcases.zip](https://github.com/RazrFalcon/resvg/files/6598935/resvg-testcases.zip)

### Testcase 1: `pattern_fill.svg`
| resvg | rsvg-convert | gerbolyze+resvg |
| --- | --- | --- |
| ![gerbolyze-fail-pattern_fill-in](https://user-images.githubusercontent.com/67436430/120812273-1fb45e00-c54d-11eb-8a47-2ca2d1213c18.png) | ![gerbolyze-fail-pattern_fill-rsvg](https://user-images.githubusercontent.com/67436430/120812320-293dc600-c54d-11eb-8a76-d887a9bc97a7.png) | ![gerbolyze-fail-pattern_fill-out](https://user-images.githubusercontent.com/67436430/120812295-2347e500-c54d-11eb-98e1-0cf21de5a13c.png) |

### Testcase 2: `pattern_stroke.svg`

| resvg | rsvg-convert | gerbolyze+resvg |
| --- | --- | --- |
| ![gerbolyze-fail-pattern_stroke-in](https://user-images.githubusercontent.com/67436430/120812387-39ee3c00-c54d-11eb-908e-168bc9919797.png) | ![gerbolyze-fail-pattern_stroke-rsvg](https://user-images.githubusercontent.com/67436430/120812407-3d81c300-c54d-11eb-91b4-6bdc51e26119.png) | ![gerbolyze-fail-pattern_stroke-out](https://user-images.githubusercontent.com/67436430/120812428-41154a00-c54d-11eb-80cc-1207ec73db2c.png) |

### Testcase 3: `pattern_stroke_dashed.svg`

| resvg | rsvg-convert | gerbolyze+resvg |
| --- | --- | --- |
| ![gerbolyze-fail-pattern_stroke_dashed-in](https://user-images.githubusercontent.com/67436430/120812453-45d9fe00-c54d-11eb-9490-a1a5d87f4b9f.png) | ![gerbolyze-fail-pattern_stroke_dashed-rsvg](https://user-images.githubusercontent.com/67436430/120812476-496d8500-c54d-11eb-80e2-e5d8e798463b.png) | ![gerbolyze-fail-pattern_stroke_dashed-out](https://user-images.githubusercontent.com/67436430/120812482-4c687580-c54d-11eb-9ee9-3dbd9d556e2a.png) |

**Comment by RazrFalcon** [comment] 2021-06-04 14:17
Yes, resvg doesn't like tiny patterns. Will see what I can do about it.

**Comment by RazrFalcon** [comment] 2023-05-21 13:46
Duplicate of #628

**Closed by RazrFalcon** 2023-05-21 13:46 UTC
