### ISSUE TITLE
textLength at textPaht not supported

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg#266] opened 2020-03-03 21:32 UTC
#### What happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/6/6b/Palestine_Ensign.svg)
|ink|![Palestine Ensign](https://user-images.githubusercontent.com/15687581/75821466-9ee14200-5d9e-11ea-9518-4cf1bc3f4706.png)
|resvg|![Palestine Ensign_resvg](https://user-images.githubusercontent.com/15687581/75821473-a1dc3280-5d9e-11ea-8906-5ea9c2bd7ad3.png)
|rsvg|![Palestine Ensign_rsvg](https://user-images.githubusercontent.com/15687581/75821479-a4d72300-5d9e-11ea-8f5c-bf0bc17a6880.png)

![Screenshot from 2020-03-03 22-32-26](https://user-images.githubusercontent.com/15687581/75821614-dfd95680-5d9e-11ea-8fcf-096da37a2b31.png)

#### What should have happened?
 - same rendering as firefox or inkscape (chrome wrong?)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Palestine_Ensign.svg

author Sarang

license https://de.wikipedia.org/wiki/Gemeinfreiheit

#### Version and Operating System:

- Inkscape Version: 0.92.4 or 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment] 2020-03-04 03:36
>chrome wrong

Why not? Even Chrome and Firefox are far from perfect.

And yes, `textLength` is not supported. See https://github.com/RazrFalcon/resvg/blob/master/docs/unsupported.md

**Comment by RazrFalcon** [comment] 2020-03-04 03:36
Duplicate of #204

**Closed by RazrFalcon** 2020-03-04 03:36 UTC
