### ISSUE TITLE
Better compute viewbox for svgs with negative coordinates

### ISSUE THREAD

**Issue by birktj** [RazrFalcon/resvg#602] opened 2023-03-29 22:37 UTC
I came across the following problem when working with font glyphs without a defined `viewBox` or `width`/`height` attributes. 
Consider the following svg:
```svg
<svg xmlns="http://www.w3.org/2000/svg">
<rect x="-50" y="-50" width="100" height="100" fill="blue"/>
<rect x="-25" y="-25" width="50" height="50" fill="red"/>
</svg>
```

Currently it is rendered as:
![test-glyph-incorrect](https://user-images.githubusercontent.com/2932651/228681199-d17261c9-3d39-4271-85cf-4d002ad13069.png)

However I would have expected something like this:
![test-glyph-correct](https://user-images.githubusercontent.com/2932651/228681253-0b2a8dc5-ff13-42f7-b5c3-7e0b57c05fa4.png)

The glyphs I came across had many negative coordinates which seems to not be handled in the current `calculate_svg_box` function. I would propose that the `calculate_svg_box` simply uses the overlap of all bboxes to compute a `viewBox`,  note that I am completely oblivious to the svg spec so if this suggestion doesn't make any sense feel free to close this issue.

https://github.com/RazrFalcon/resvg/blob/2c5d90990411535c1afddb62b8be85076db05277/usvg-parser/src/converter.rs#L206-L228

**Comment by RazrFalcon** [comment] 2023-03-30 14:28
This is the expected behavior. Browsers would render your SVG the same way.

My advice: never rely on SVG size auto-detection. It doesn't work as people expect. You can find more details [here](https://razrfalcon.github.io/notes-on-svg-parsing/auto-size.html).

I'm not sure how we can improve this. Adding a flag the would force a different bbox calculation algorithm seems like the only option. But I'm not interested in maintaining it. I was agains this feature to begin with, because how useless it is when implemented according to the spec.

**Comment by RazrFalcon** [comment] 2023-04-10 00:01
Out of scope.

**Closed by RazrFalcon** 2023-04-10 00:01 UTC
