### ISSUE TITLE
Font width issues

### ISSUE THREAD

**Issue by ullenboom** [RazrFalcon/resvg#556] opened 2022-11-15 09:10 UTC
Rending an SVG is leading into different font width.

Generated PNG from resvg:

![AuthenticationManager_ProviderManager-generated](https://user-images.githubusercontent.com/5071169/201877528-990188ad-4094-467a-853d-3a2d42b732c0.png)

Original (from PlantUML):

![AuthenticationManager_ProviderManager](https://user-images.githubusercontent.com/5071169/201877531-f626ab26-a91c-4f90-ae69-38071d500825.svg)

skinparam defaultFontName PT Sans

**Comment by RazrFalcon** [comment] 2022-11-15 09:28
Yes, this is a known issue.

**Comment by RazrFalcon** [comment] 2022-11-15 09:28
Duplicate of #204

**Closed by RazrFalcon** 2022-11-15 09:28 UTC
